### ISSUE TITLE
function names need to use frankenstyle prefix

### ISSUE THREAD

**Issue by danmarsden** [webers-technikum-wien/moodle-local_macromucho#1]
The functions in lib.php need to use the correct frankenstyle prefix eg:
"pick_fraction" 
should be:
"local_macromucho_pick_fraction"

more info: https://docs.moodle.org/dev/Frankenstyle#Function_names

**Comment by danmarsden** [comment]
macromuch_form.php class macromiucho_form should also really be namespaced or renamed to:
local_macromucho_form

**Comment by stemiwe** [comment]
fixed these issues, fingers crossed :)
